meta_product_name: "Photo buddies"
meta_title: "Photo buddies - Find your local community!"
meta_description: "Explore the community!"
meta_image: "transparant_logo_resize.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
